services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped

    environment:
      - PUID=0
      - PGID=0

    volumes:
      - nextcloud-data:/config
      - /srv/cloud:/data
    ports:
      - 5000:80


volumes:
  nextcloud-data:
  onlyoffice-data: