services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    environment:
      - PUID=0
      - PGID=0

    devices:
    - /dev/dri:/dev/dri 
    volumes:
      - jellyfin-data:/config
      - /srv/media/tv:/data/tvshows
      - /srv/media/movies:/data/movies
    ports:
      - 8000:8096


  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped

    ports:
      - 8001:5055
    volumes:
      - jellyseerr-data:/app/config
    depends_on:
      - jellyfin


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    environment:
      - PUID=0
      - PGID=0
      - WEBUI_PORT=8002
      - TORRENTING_PORT=6881

    volumes:
      - qbittorrent-data:/config
      - /srv/media/downloads:/downloads
    ports:
      - 8002:8002
      - 6881:6881
      - 6881:6881/udp


  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    restart: unless-stopped


  health-checker:
    build: ./Images/HealthChecker
    container_name: health-checker
    restart: unless-stopped

    depends_on:
      - radarr
      - sonarr

    

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped

    volumes:
      - powlarr-data:/config
    ports:
      - 8010:9696
    depends_on:
      - qbittorrent
      - flaresolverr


  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped

    environment:
      - PUID=0
      - PGID=0

    ports:
      - "8011:8989"
    volumes:
      - sonarr-data:/config
      - /srv/media/tv:/tv
      - /srv/media/downloads/:/downloads
    depends_on:
      - prowlarr


  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped

    environment:
      - PUID=0
      - PGID=0

    ports:
      - "8012:7878"
    volumes:
      - radarr-data:/config
      - /srv/media/movies:/movies
      - /srv/media/downloads/:/downloads
    depends_on:
      - prowlarr




volumes:
  jellyfin-data:
  jellyseerr-data:

  qbittorrent-data:

  powlarr-data:

  sonarr-data:
  radarr-data: