services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped

    ports:
      - "4000:4533"
    volumes:
      - "/srv/music:/music:ro"
      - "navidrome-data:/data"


  deemix:
    image: finniedj/deemix
    container_name: deemix
    restart: unless-stopped

    volumes:
      - /srv/music/:/downloads
      - deemix-data:/config
    ports:
      - 4001:6595


c
volumes:
  navidrome-data:
  deemix-data:
