# ==================
# Window Settings
# ==================
[window]
decorations = "full"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 6
y = 6

# ==================
# Environment
# ==================
[env]
TERM = "xterm-256color"

# ==================
# General Settings
# ==================
[general]
import = ["./themes/themes/gruvbox_dark.toml"]

# ==================
# Font Configuration
# ==================
[font]
size = 12.0
